# Generated by Django 4.0 on 2022-01-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('department_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(max_length=8),
        ),
    ]
